---
- name: Restore inventory database if not present
  hosts: db_servers

  tasks:
    - name: Make sure inventory database exists
      mysql_db:
        name: inventory
        state: present
      register: inventory_present

    - name: Copy database backup file to host if not present
      copy:
        src: files/inventory-database.sql
        dest: /srv
      when:
        - inventory_present['changed'] == false

    - name: Restore inventory backup data
      mysql_db:
        name: inventory
        state: import
        target: /srv/inventory-database.sql
      when: inventory_present['changed'] == false
